### ISSUE TITLE
运行代码出现了keyerror：0的报错 的可能原因

### ISSUE THREAD

**Issue by fengxy369** [ShiroDoMain/Attention_LSTM_RUL_Prediction#1]
Hello, have you published a paper about this code? Or is this code a copy of one of your papers？Could you please provide the title of the paper, if any?（您好，请问您关于这份代码发表了相关论文吗？或者说，这份代码是您复现的哪篇论文吗？如果有的话，您是否可以提供一下论文标题？）

**Comment by nostalgicality** [comment]
Me too,my pycharm was wrong too.KeyError: 0.
Could you please provide the title of the paper for me if it is convenient for you.Thanks!

**Comment by ShiroDoMain** [comment]
fixed
