### ISSUE TITLE
Could you please provide the title of the paper, if any?

### ISSUE THREAD

**Issue by fengxy369** [ShiroDoMain/Attention_LSTM_RUL_Prediction#2]
Hello, have you published a paper about this code? Or is this code a copy of one of your papers？Could you please provide the title of the paper, if any?（您好，请问您关于这份代码发表了相关论文吗？或者说，这份代码是您复现的哪篇论文吗？如果有的话，您是否可以提供一下论文标题？）

**Comment by ShiroDoMain** [comment]
您好，关于此代码我并没有发表过论文，该代码只是很久之前初学LSTM时一时兴起写的

**Comment by fengxy369** [comment]
> 您好，关于此代码我并没有发表过论文，该代码只是很久之前初学LSTM时一时兴起写的

哇塞，那您写的真好，那请问您构建这个网络的时候，有参考什么架构吗？因为我初学深度学习，不是很明白这个网络的架构是如何构建的！

**Comment by ShiroDoMain** [comment]
> 

我参考了的是一个包含了LSTM attention+Channel attention的Transformer框架，该代码因为时间太久已经忘了当时是怎么想着写出来的了，并不具有太大的参考价值，现在看来其中的漏洞也很多。但是本人因为学业繁忙，可能短时间内并没有空余时间来整理重构改代码

**Comment by fengxy369** [comment]
> > 
> 
> 我参考了的是一个包含了LSTM attention+Channel attention的Transformer框架，该代码因为时间太久已经忘了当时是怎么想着写出来的了，并不具有太大的参考价值，现在看来其中的漏洞也很多。但是本人因为学业繁忙，可能短时间内并没有空余时间来整理重构改代码

好的，谢谢您
